[package]
name = "memorize_func"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.17.1"
lru = "0.10.0"
memorize_func_macro = { path = "memorize_func_macro"}